// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5HEOkP8o6ATgFWuQF-ticI6Fw2H6dihc',
    appId: '1:768043028815:android:83e985bf937351c97b353a',
    messagingSenderId: '768043028815',
    projectId: 'uclap-e03fe',
    databaseURL: 'https://uclap-e03fe-default-rtdb.firebaseio.com',
    storageBucket: 'uclap-e03fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYnqR4Ky2aceNWSx8U1cxQB4RAUlaD754',
    appId: '1:768043028815:ios:1aa9fd0fc99431bf7b353a',
    messagingSenderId: '768043028815',
    projectId: 'uclap-e03fe',
    databaseURL: 'https://uclap-e03fe-default-rtdb.firebaseio.com',
    storageBucket: 'uclap-e03fe.appspot.com',
    iosBundleId: 'com.hellochotu.customerapps',
  );
}
